### ISSUE TITLE
Better explanation for advanced rate limit addon.

### ISSUE THREAD

**Issue by yolossn** [Kong/docs.konghq.com#2382]
- `docs.konghq.com` url(s): https://docs.konghq.com/hub/kong-inc/rate-limiting-advanced/

### Summary
The doc just says that the advanced plugin has  `greatly enhanced configuration options and performance`  than the rate limit addon. It is not clear what kind of additional configuration options are provided and how much the performance varies. 
A better explanation of this will be handy to decide if I should opt for enterprise plan.

**Comment by tlblessing** [comment]
Added to my DOC ticket https://konghq.atlassian.net/browse/DOCS-1417

**Comment by sanyer** [comment]
@yolossn doc mentions enhanced but not additional configuration options for this plugin.
The biggest different in configuration if very straightforward if you used any of these two plugins before:

rate-limiting-advanced uses `limit` and `window_size` options instead of `second, minute, hour, day, month, year` for rate-limiting. It is explained on the bottom of the page.

But performance claim is not explained, that's true. Perhaps option `sync_rate` has something to do with it.

**Comment by yolossn** [comment]
@sanyer Thanks for the clarification.

**Comment by falondarville** [comment]
@yolossn - thank you for your question. I will update the documentation to be less ambiguous. The following was confirmed by our Rate Limiting Advanced plugin engineering team. 

As compared to the standard Rate Limiting plugin, Rate Limiting Advanced provides the additional configurations: `limit`, `window_size`, and `sync_rate`. It also has support for redis sentinel, redis cluster, and redis SSL.

In addition, the user has more rate limiting algorithms to choose from.  These are more accurate as they enable configuration at a higher level of specificity. Learn more about our algorithms here: https://konghq.com/blog/how-to-design-a-scalable-rate-limiting-algorithm/

Regarding performance, Rate Limiting Advanced has better throughput performance with better accuracy. Configure `sync_rate` to periodically sync with backend storage.
