### ISSUE TITLE
Add Konnect specific instructions for Adding Certificate Authorities

### ISSUE THREAD

**Issue by eshih** [Kong/docs.konghq.com#3451]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/mtls-auth/#adding-certificate-authorities

### What happened?

The provided `curl` example will not work with Konnect instances since the Control Plane is not accessible directly. 

### What did you expect to happen?

Should include either screenshots or directions to add certificates via 
1. UI (Shared Config > Certificates > New Certificate) 
2. curl command that works with the Konnect admin such as: 
```
curl -sX POST https:konnect.konghq.com/api/control_planes/[Konnect-id]/ca_certificates -F cert=@testCACert.pem --cookie '[generated access cookie]'
```

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by eshih** [comment]
Happy to make a PR, but not sure how best add the info. Maybe a `navtab` for konnect specific?

**Comment by lena-larionova** [comment]
Hey @eshih ! Thanks for catching this. For this specific topic, since using mtls and using certs is important for Konnect, you're welcome to edit it. I agree - a `navtabs` element would be the way to go.

Unfortunately, this is also a symptom of a much bigger issue - none of the plugin docs provide Konnect API examples, and there are a lot of them.  We have an overhaul of the plugin hub planned for next year, so I'm adding the issue of tackling further Konnect examples to the list.

**Comment by eshih** [comment]
Sorry for the delay @lena-larionova I wasn't getting my email notifications in so I didn't see your comment. I've put in a PR to try to update the page!

**Comment by eshih** [comment]
Completed with PR #3495
