### ISSUE TITLE
[docs] Redirect to the same page when change version

### ISSUE THREAD

**Issue by codebien** [Kong/docs.konghq.com#413]
When change version not redirect to the index version page, instead redirect to the same page.

**Comment by thibaultcha** [comment]
Hi,

That would be great indeed. Mind contributing a PR for it?

**Comment by vividh** [comment]
May I take a stab at this?

**Comment by coopr** [comment]
Certainly @vividh ! 

A naive implementation would have the version picker essentially just put the selected version number in the URL - for example, if you were on page https://docs.konghq.com/0.14.x/auth/ and you used the version picker to switch to version 0.12.x, you'd be sent to page https://docs.konghq.com/0.12.x/auth/

The only catch with that approach is that not all versions have all the same pages - so there would need to be some sort of fallback in which if you were on https://docs.konghq.com/0.14.x/auth/ and you switched to version 0.3.x, instead of going to https://docs.konghq.com/0.3.x/auth/ (which doesn't exist and returns 404, which isn't a good experience ;) you'd instead be taken to that new version's home page (https://docs.konghq.com/0.3.x/ in this case)

I welcome your ideas about how to handle this!

**Comment by vividh** [comment]
Oh nice, that adds an extra dimension to tackling this problem! Will think about an approach for this.

**Comment by vividh** [comment]
Created PR so that the discussion can be more concrete in terms of the changes required. Also, it would be helpful to track all the articles that require configuration for this feature. Please share your inputs there!

**Comment by lena-larionova** [comment]
Not sure what happened between the last merged change and this year, but it looks like we lost this ability at some point. Fixed once again in https://github.com/Kong/docs.konghq.com/pull/2043
