### ISSUE TITLE
Upstream timeout plugin has no compatibility in the  ENTERPRISE column

### ISSUE THREAD

**Issue by chaofan-nirvana** [Kong/docs.konghq.com#5129]
### Where is the problem?

https://docs.konghq.com/konnect/compatibility/#plugin-compatibility

### What happened?

Missing the content of "Upstream Timeout"  in the ENTERPRISE column. What does it mean?
![image](https://user-images.githubusercontent.com/28529650/217481346-e8ec1b79-ef68-414d-bdb7-b365dba4f4f2.png)
the 

### What did you expect to happen?

"Upstream Timeout" should have a result in the ENTERPRISE column. If not, there should be some explanation about this.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Thanks for catching this!
This is due to a typo. The plugin is supported in Enterprise, and I have an open PR (https://github.com/Kong/docs.konghq.com/pull/5108) that will fix it (among other things), planned to be merged next week.

https://github.com/Kong/docs.konghq.com/pull/5108/files#diff-3f946b875b4f65a313a0ae4c7ddee12cd3d8477e801d354acaff905f5f71f4c7R400
