### ISSUE TITLE
Version 0.13.x and Idempotency

### ISSUE THREAD

**Issue by adamdyson** [Kong/docs.konghq.com#617]
I have been watching the development of Kong closely since reading about the changes introduced in version `0.13.x`, in particular the decoupling of API's with Services and Routes.

A major reason for considering using Kong on a future project, was the fact that all aspects of managing API's can be done using an API itself (Admin API). To aid in managing the API's, there's the commercial Admin GUI offered in the Enterprise Edition as well as many other open-source projects. However, I would like to automate and manage the API's using [Ansible](https://www.ansible.com).

The purpose of using a tool like Ansible, is to ensure the software (Kong) being provisioned is idempotent. E.g. if you make a change by adding an API, running the same procedure again would result in no change. I have started developing an Ansible module and have noticed some inconsistencies and potential problems that may prevent or make this difficult to achieve.

When starting development on the Ansible module, I began with the `Service` entity and endpoints because it seemed to be at the top of the hierarchy, as far as no other entities depending on it. Being able to `list`, `find`, `update_or_create` and `delete_by_name` while being idempotent was relatively easy, given that the `Service` entity has a unique identifier `name` which isn't auto-generated.

Below is an example of how services can be managed using the module.

```yml
- name: List all services
  kong_service:
    state: list

- name: Find a service by name
  kong_service:
    name: example-service
    state: find

- name: Add a service
  kong_service:
    name: example-service
    host: example.com
    state: present

- name: Delete a service
  kong_service:
    name: example-service
    state: absent
```

Below is the basic code written to implement the API calls.

```python
class KongServiceApi(KongApi):

    def update_or_create(self):

        exists = self.request('/services/{name}', 'GET')

        if exists['status'] == 200:
            result = self.request('/services/{name}', 'PATCH', self.data)
            result['changed'] = self.changed(exists['output'], result['output'])
        else:
            result = self.request('/services', 'POST', self.data)
            result['changed'] = result['status'] == 201

        result['failed'] = result['status'] >= 400

        return result

    def delete_by_name(self):

        exists = self.request('/services/{name}', 'GET')
        result = self.request('/services/{name}', 'DELETE')
        result['failed'] = result['status'] >= 400
        result['changed'] = exists['status'] == 200 and result['status'] == 204

        return result

    def find_by_name(self):

        return self.request('/services/{name}', 'GET')

    def list(self):

        return self.request('/services', 'GET')
```

**FYI:** I noticed the [services](https://github.com/Kong/kong/blob/0.13.0rc2/kong/api/routes/services.lua) route doesn't include a `PUT` method for Updating or Creating a `Service`, unlike the deprecated [apis](https://github.com/Kong/kong/blob/0.13.0rc2/kong/api/routes/apis.lua) route. I'm not sure if this is intentional or an oversight.

## Feature request

Looking at the code above, you might have noticed multiple requests were made in order to make updating, creating and deleting a `Service` idempotent. Also to make Updating or Creating a `Service` idempotent I had to determine whether any properties had changed by comparing each value (while ignoring the `updated_at` field) in the existing entity with the values returned after making a `PATCH` request.

Honestly I can deal with this, but I wonder if automating Kong could be simplified if a few changes were made. Now I'm not familiar with Kong's database abstraction layer, but in most cases a value is returned when deleting a row from the database, E.g. the number of effected rows. If Kong was to utilise such information and determine changes to entities internally for `PUT` requests, returning a custom HTTP header in the response would mean the code above could look like this.

```python
class KongServiceApi(KongApi):

    def update_or_create(self):

        result = self.request('/services/{name}', 'PUT', self.data)
        # Determine changes by custom HTTP header value
        result['changed'] = result['headers']['Changed'] == 1
        result['failed'] = result['status'] >= 400

        return result

    def delete_by_name(self):

        result = self.request('/services/{name}', 'DELETE')
        # Determine changes by custom HTTP header value
        result['changed'] = result['headers']['Changed'] == 1
        result['failed'] = result['status'] >= 400

        return result

    def find_by_name(self):

        return self.request('/services/{name}', 'GET')

    def list(self):

        return self.request('/services', 'GET')
```

## Problem

Once I was able to successfully manage `Service` entities in an idempotent way, I was exited to begin developing something similar for managing `Route` entities and endpoints. However looking at the route [schema](https://github.com/Kong/kong/blob/0.13.0rc2/kong/db/schema/entities/routes.lua), [routes](https://github.com/Kong/kong/blob/0.13.0rc2/kong/api/routes/routes.lua) and [documentation](https://github.com/Kong/getkong.org/blob/0.13.x/app/docs/0.13.x/admin-api.md) I can't see how this would be possible.

In order to make managing `Route` entities (and possibly others) in the same way I have for `Service` entities, you really need a property that can be referenced, which is unique and not automatically generated.

I suggest that any entity which cannot be referenced in such a way, include an optional property `identifier`. Then [routes](https://github.com/Kong/kong/tree/0.13.0rc2/kong/api/routes) could be updated to consider not only the `id` but also `identifier` when performing CRUD operations. In the same way routes for services consider both the `id` and `name` properties.

If introduced, the `identifier` property would be optional and would really only serve a purpose for those wanting to automate Kong. But because it is optional, existing projects would not break and GUI's would simply ignore it.

I look forward to hearing your thoughts.

**Comment by adamdyson** [comment]
I have been thinking about this some more, there may be an easier was to solve the problem above regarding idempotency.

Would it be possible for Kong to allow/use an `id` value if specified when creating a `Route` (and other entities), rather than always generating a UUID?

When I became frustrated not being able to automate Kong fully, I started looking at other API Gateway's such as [Krakend](http://www.krakend.io/docs/overview/configuration/) & [Vulcand](http://vulcand.readthedocs.io) to see how easy they could be automated. Both of which take a similar approach allowing the end-user you to specify your own `id`. 

I thought I would try this with Kong to see what happens. But even when specifying an `id` value in the correct UUID format, Kong ignores it.

```yml
- name: Add a service
  kong_service:
    name: example-service
    host: example.com
    state: present

- name: Add a route
  kong_route:
    id: 8189386d-24f7-47e8-aba3-7a4a5be993a5
    service: example-service
    hosts: [example.com]
    paths: [/request]
    state: present
```

The Ansible task above *Add a route* would post the data below to the following endpoint `http://localhost:8001/services/example-service/routes`

```json
{
    "id": "8189386d-24f7-47e8-aba3-7a4a5be993a1",
    "data": {
        "hosts": [
            "example.com"
        ],  
        "paths": [
            "/request"
        ]
    }
}
```

```json
ok: [local.adam] => {
    "result": {
        "changed": true, 
        "failed": false, 
        "msg": "OK (unknown bytes)", 
        "output": {
            "created_at": 1521273275, 
            "hosts": [
                "example.com"
            ], 
            "id": "3d315af3-1c42-413a-a36e-d48553e24ea9", 
            "methods": null, 
            "paths": [
                "/request"
            ], 
            "preserve_host": false, 
            "protocols": [
                "http", 
                "https"
            ], 
            "regex_priority": 0, 
            "service": {
                "id": "9be03e50-a20b-4d4a-9772-269016555582"
            }, 
            "strip_path": true, 
            "updated_at": 1521273275
        }, 
        "status": 201, 
        "url": "http://localhost:8001/services/example-service/routes"
    }
}
```

You'll notice in the result output, even though specifying an `id` of `8189386d-24f7-47e8-aba3-7a4a5be993a5` Kong generates and returns an `id` of `3d315af3-1c42-413a-a36e-d48553e24ea9`. Making it impossible to automate.

**Comment by bungle** [comment]
@adamdyson thank you for your very thorough explanation of the issues you are facing with new model APIs. Good thing is that the APIs are now auto-generated, so we can have fix written once. Let us think about this a bit.

**Comment by bungle** [comment]
Just a quick update. There is a great change you get what you want if/when we implement `PUT`.  `POST` is not idempotent. The `DELETE` is a bit controversial. It is said to be idempotent, and that is exactly what it is with Kong new Admin API for routes and Services (it always returns `NO CONTENT`, unless there is an error, and not found is not consider an error here — the DAO will give you feedback of not found, our ReST api doesn't, and that's why you may except it to be idempotent). What you clearly want is something like:

```
PUT /services/{service-id}
```

and same for other entities. One thing that makes this a bit more complex is the possibility of composite primary keys. This is not very hard to implement, we just want to think about it a bit. On APIs you had something like:

```
PUT /apis
```

Which is not correct, and you didn't have (unless you wanted to replace whole `apis`, which it clearly did not do):

```
PUT /apis/{api-id}
```

**Comment by thibaultcha** [comment]
Hi @adamdyson,

Good points - most of them with underlying reasons we can detail here, so let's do that.

Before we dig into any detail of the Admin API itself (and the custom code you had to write to handle idempotency), I would like to mention a couple things:

1. We have plans to support _native_ declarative configuration in an idempotent fashion in the future. For now, the Admin API still is the only way to natively configure Kong (or the GUI in Enterprise), but that will improve.
2. As of today, there exists [kongfig](https://github.com/mybuilder/kongfig) which is a community-maintained tool aiming at solving declarative configuration (so that you do not have to write your own scripts for it), and, although I never used it myself, I seem to recall that you could handle idempotency by using various "attributes" for each entity (like "ensure").

Now, about your interrogations.

> FYI: I noticed the services route doesn't include a PUT method for Updating or Creating a Service, unlike the deprecated apis route. I'm not sure if this is intentional or an oversight.

With Routes and Services comes a new implementation of the Admin API (with many benefits regarding form-encoded payloads parsing and error reporting). One of the mistakes the _old_ Admin API (`/apis`, `/consumers`, etc...) made is not implementing a proper interpretation of `PUT`. In the old Admin API, using `PUT` must be made on the collection endpoints (e.g. `/apis`) and will "create or update", and will even do so with a lot of magic happening, so much that your payload and what gets inserted or updated in the database can be completely different. We both know this isn't how `PUT` should work.

In the new Admin API we decided to not repeat that mistake, but because of time constraints and since only 2 new endpoints are introduced (with `/apis` still being there), we did not consider `PUT` to be among our top priorities, so we are releasing 0.13.0 without support for `PUT` in `/routes` and `/services`. We will add (proper) support for it later (and once more endpoints use the new Admin API).

 > Looking at the code above, you might have noticed multiple requests were made in order to make updating, creating and deleting a Service idempotent.

I believe this is how Kongfig implements their idempotency as well, and we do acknowledge that this is less than ideal. Implementing `PUT`, for example, or a native declarative configuration tool, as mentioned above. Eventually one day, both.

> If introduced, the identifier property would be optional and would really only serve a purpose for those wanting to automate Kong. But because it is optional, existing projects would not break and GUI's would simply ignore it.

If everything had a name, it would be useful for this, but not everything deserves such a name (most Routes do not, hence why Routes don't have a name). Services do have a name because most likely, they are the representation of one of your existing Services (that your business, certainly, has named).

> Would it be possible for Kong to allow/use an id value if specified when creating a Route (and other entities), rather than always generating a UUID?

One of the struggles we encounter developing Kong is ensuring the interoperability of both PostgreSQL and Cassandra, which as you can imagine, is a daunting task and somewhat doomed (we are always limiting one of the two due to shortcomings of the nature of the other).
The reason we use UUIDs is because of Cassandra, and the high-cardinality requirements of the primary keys of its tables. Why using UUIDs in PostgreSQL when we can avoid it then? Simply put: interoperability, time constraints, and business requirements.

> I thought I would try this with Kong to see what happens. But even when specifying an id value in the correct UUID format, Kong ignores it.

Correct. Only a `PUT` on one of the old collection endpoints (e.g. `/apis`) with an `id` in the body will be taken into consideration. Again, an incorrect implementation of `PUT`.

As of today, the `GET`/`DELETE`/`POST` dance seems to be your only option - although we will be improving that in the future.

**Comment by adamdyson** [comment]
Hi @thibaultcha 

Thanks for thorough explanation. Since the changes introduced in v0.14.0 I have been able configure Kong with Ansible in an idempotent way. The source code for the Ansible role can be found [here](https://github.com/ontic/ansible-role-kong) if you're interested in knowing more.

I've chosen a different path and implementation from [kongfig](https://github.com/mybuilder/kongfig). There are no dependencies or additional software to install, idempotency was achieved by specifying an `id` for each module which then gets converted to a UUID.

```
- name: 'Create a service'
  kong_service:
    id: 'example-service'
    name: 'example-service'
    url: 'http://mockbin.org/request'
    action: 'create'
- name: 'Create a route'
  kong_route:
    id: 'example-route'
    service: 'example-service'
    hosts: 'example.com'
    action: 'create'
- name: 'Create a consumer'
  kong_consumer:
    id: 'example-consumer'
    username: 'adam'
    custom_id: '1234'
    action: 'create'
- name: 'Create a plugin'
  kong_plugin:
    id: 'example-plugin'
    route: 'example-route'
    name: 'key-auth'
    enabled: true
    action: 'create'
```

**Comment by thibaultcha** [comment]
@adamdyson Glad to hear! Indeed 0.14.0 introduced support for PUT :) 

Closing this and considering it resolved then!
