### ISSUE TITLE
[Meta] How should we handle deprecated plugins?

### ISSUE THREAD

**Issue by nijikokun** [Kong/docs.konghq.com#661]
What should be the process for deprecating plugins such as [Dynamic SSL](https://getkong.org/plugins/dynamic-ssl) which is still displayed on the [plugins](https://konghq.com/plugins/) page and is only supported in 0.10 given that we are on 0.13 now?

**Comment by thibaultcha** [comment]
Dynamic SSL is not deprecated, but removed. It probably be deleted and wiped out of the documentation, since it is both so old and wrongly implemented (does not fit in the Kong plugins paradigm). I've been wanting to do that for a while.

Other currently deprecated plugins would as of today receive a yellow alert toolbox. If we want to design some special UI for it, that's fine, even if maybe unnecessary. It is worth noting that the currently only deprecated plugin (galileo) is already not visible in the documentation already.

One thought: if we ever version our plugins, it'd be great to have such deprecation notices be visible on all versions of said plugin's doc, since it'd be a shame for a user to start using a plugin by reading its old documentation, only to find out that the "latest" Kong version deprecates it. Also, in the future when plugins are not part of the core anymore, this discussion probably requires us taking another angle at the issue, because of the added flexibility and release cycles of said plugins.

**Comment by coopr** [comment]
@thibaultcha @nijikokun I've PR'ed removal of the Dynamic SSL plugin.

Have a look at https://docs.konghq.com/hub/ and LMK if you'd like to see any other plugins removed, or if warnings should be added to any plugins. 

The launch of Kong Hub brought us the ability to version plugin's documentation - but there are still some missing features, like a warning that shows when you are on an older version of a plugin (for example, the top of this page https://docs.konghq.com/0.12.x/auth/ shows a warning, but the top of this page https://docs.konghq.com/hub/kong-inc/oauth2-introspection/0.31-x.html does not) - we'll solve that with https://github.com/Kong/docs.konghq.com/issues/893

If you think this issue is sufficiently solved, please close it, TIA!

**Comment by thibaultcha** [comment]
@coopr Thank you! This can be close now imho. DynamicSSL is removed, and the Hub can keep plugins with several versions, which I believe answers the second half of this issue.
