### ISSUE TITLE
ACME Plugin not working as per the step mentioned in doc's

### ISSUE THREAD

**Issue by nehaDumbo15** [Kong/docs.konghq.com#7966]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/acme/how-to/local-testing-development/

### What happened?

**The step mentioned to use kong acme plugin in local environment using ngrok its not working.
Also the other step in using the plugin is mentioned is not working.
Is there any issue with this plugin in hybrid mode ??** 

### What did you expect to happen?

Improve the document with whole configuration of service + route + plugin by taking example of any domain

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Did a bit more digging, and it turns out there are some caveats for hybrid mode: tl;dr, the `shm` storage type doesn't work in hybrid mode. Since that is the default storage type, if you run through the tutorial without changing the storage type in hybrid or Konnect, it just won't work. 

All the info is here: https://docs.konghq.com/hub/kong-inc/acme/#hybrid-mode-workflow 

I'll make sure to update the guide with a hybrid mode option/comment/note.
