### ISSUE TITLE
Upgrade to modern version of Jekyll and use kramdown

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#933]
#920 reminded us that our older versions of Jekyll, and using redcarpet instead of kramdown for rendering Markdown, are causing various problems.

**Comment by vividh** [comment]
Hi, I went through #920 to understand the motivation behind this issue. I would like to work on this.

To start with, I ran the project locally with the following changes in `jekyll.yml`:

```diff
+markdown: kramdown
-markdown: redcarpet
- redcarpet:
-   extensions:
-     - fenced_code_blocks
-     - no_intra_emphasis
-     - autolink
-     - with_toc_data
-     - strikethrough
-     - lax_html_blocks
-     - superscript
-     - tables
```

Looking at the redcarpet extensions I expected some issues in the final built docs, especially with code snippets and tables, but surprisingly the kramdown build looks to be the same as redcarpet.
Is this expected?

Can you guide me as to how I can check feature parity with the current docs site?

Also, can you point me to few articles in the docs where I can confirm if the [duplicate IDs issue](https://github.com/Kong/docs.konghq.com/pull/920#issuecomment-428736885) has been fixed by switching to kramdown?

**Comment by coopr** [comment]
Hello @vividh - thanks for your interest! 

> Hi, I went through #920 to understand the motivation behind this issue. I would like to work on this.
Awesome! I'm here to help :)
 
> To start with, I ran the project locally with the following changes in `jekyll.yml`:
> 
> ```diff
> +markdown: kramdown
> -markdown: redcarpet
> - redcarpet:
> -   extensions:
> -     - fenced_code_blocks
> -     - no_intra_emphasis
> -     - autolink
> -     - with_toc_data
> -     - strikethrough
> -     - lax_html_blocks
> -     - superscript
> -     - tables
> ```
> 
> Looking at the redcarpet extensions I expected some issues in the final built docs, especially with code snippets and tables, but surprisingly the kramdown build looks to be the same as redcarpet.
> Is this expected?

I don't know - I'm afraid I don't know enough about how this all works to be able to predict the effect of this change. 

Hopefully @allejo could come comment here, as his terrific work on https://github.com/Kong/docs.konghq.com/pull/920 makes him better qualified than I to do so.
 
> Can you guide me as to how I can check feature parity with the current docs site?

Off the top of my head:
1. Run the site locally, with your change
2. Visit a bunch of pages, and compare them (visually) to the pages on the current production site at https://docs.konghq.com/
3. Try out the Table of Contents on a few pages in the https://docs.konghq.com/latest/ and https://docs.konghq.com/enterprise/ and https://docs.konghq.com/hub/ parts of the site to ensure they work as expected
4. Try out the sidebar links on those pages

> Also, can you point me to few articles in the docs where I can confirm if the [duplicate IDs issue](https://github.com/Kong/docs.konghq.com/pull/920#issuecomment-428736885) has been fixed by switching to kramdown?

Great question! This page https://docs.konghq.com/enterprise/changelog/ _used_ to show the duplicate ID problem, but then we "fixed" it by changing the otherwise duplicate headers to plain old *bold* text here https://github.com/Kong/docs.konghq.com/pull/920/files#diff-1f5b1371b59158788d4a59f3089d44d0

A similar fix occurred here https://github.com/Kong/docs.konghq.com/pull/932/files  

I guess you could try reverting one of those changes, or manually editing a page to have what would otherwise be duplicate IDs?

**Comment by coopr** [comment]
Ah, I found a live page with the duplicate IDs issue: https://docs.konghq.com/0.14.x/admin-api/

**Comment by allejo** [comment]
> I don't know - I'm afraid I don't know enough about how this all works to be able to predict the effect of this change.
> 
> Hopefully @allejo could come comment here, as his terrific work on #920 makes him better qualified than I to do so.

Based on the [redcarpet README](https://github.com/vmg/redcarpet#redcarpet-is-written-with-sugar-spice-and-everything-nice), here's what I've concluded based on the redcarpet usage Kong is using.

redcarpet          | kramdown
------------------ | ---------
fenced_code_blocks | :white_check_mark:
no_intra_emphasis  | :white_check_mark:
autolink           | :x:
with_toc_data      | :white_check_mark:
strikethrough      | :white_check_mark:
lax_html_blocks    | :question:
superscript        | :x:
tables             | :white_check_mark:

I can't seem to find what exactly `lax_html_blocks` does but by the sounds of it, I would *think* that it means parse markdown inside of HTML elements.

So in order to make sure kramdown works,

- the docs would need to look for any superscript uses and replace it with manual `<sup></sup>` calls
- Autolinks should be replaced with proper links
- if there is any markdown inside of HTML blocks, they should be replaced with [`markdown="1"`](https://kramdown.gettalong.org/syntax.html#html-blocks)

Everything else, *should* be compatible with kramdown but a double check through the important and current pages would be ideal.

**Comment by vividh** [comment]
Thanks @allejo! Will do the parity checks locally for all these features and give an update.
